version: "3.9"

services:
  manager:
    image: cr.selcloud.ru/rrr/events-manager
    build:
      dockerfile: Dockerfile
    volumes:
      - /root/uploads:/work/uploads
      - /root/logs:/work/logs
    restart: unless-stopped
    environment:
      - DB_USER=manager
      - DB_PASSWORD=qwerty
      - DB_URL=jdbc:postgresql://db:5432/manager
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
  db:
    image: "postgres:12.19-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5432:5432"
    volumes:
        - data-volume:/var/lib/postgresql/data
  adminer:
    image: adminer:4.8.1-standalone
  portainer:
    image: portainer/portainer-ce:2.20.2-alpine
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  nginx:
    restart: unless-stopped
    image: cr.selcloud.ru/rrr/events-nginx

    build:
      dockerfile: nginx.Dockerfile
      args:
        - NGINX_PASS=${ADMIN_PASS}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "443:443/tcp"
      - "80:80/tcp"


volumes:
  data-volume:
  grafana-persistent:
  prometheus-persistent:
  portainer_data: