name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    -  name: Login to private registry
       uses: docker/login-action@v1
       with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Docker images
      run: ADMIN_PASS=${{ secrets.ADMIN_PASS }} docker compose build

    - name: Publish Docker images
      run: ADMIN_PASS=${{ secrets.ADMIN_PASS }} docker compose push
